### ISSUE TITLE
create image display function

### ISSUE THREAD

**Issue by gs172** [JellyEvan/547final_jks#12]
simple function to display processed OCT B-scan

**Comment by JellyEvan** [comment]
i'm having a problem getting an PNG file to load with Pillow i don't know if its too big or if PNG have extra layers or something but using this example [image](https://github.com/JellyEvan/547final_jks/blob/GUI_init/static/tape_avg.png)

and the following code:
`from PIL import Image, ImageTk
import tkinter as tk

root = tk.Tk()
img = Image.open("./static/tape_avg.png").convert("RGB")

tkimage = ImageTk.PhotoImage(img)
tk.Label(root, image=tkimage).pack()
root.mainloop()`

i just get a blank window the size of the image, any thoughts?

**Comment by dward2** [comment]
I'm away from my computer, so I can't investigate in depth, but one issue could be that Python's garbage collection destroys the climate variable so it cannot be displayed properly, a sort of bug in printer.

Try this:  assign your Label to a variable such as:

mylabel = ttk.Label...

Then, add the line:

mylabel.label = tkimage

This should attach the variable to the label so it isn't captured in garbage collection.

Give this a try.  I'm pulling the syntax out of memory, so might be a bit off.  If it doesn't work, let me know and when I am back to the computer, I can take a more detailed look.

Dr. Ward



________________________________

**Comment by dward2** [comment]
@JellyEvan Did the above work to address the blank image?  Or, is this still an outstanding issue?

**Comment by JellyEvan** [comment]
@wesleyk-duke,  the only way I got it to work was to draw a canvas over the entire window, and then fix all my widgets to the canvas. The png had no problems there. I tried creating a reference label and a few other things nothing else worked. Thanks, Evan

**Comment by dward2** [comment]
I did see on one website a preference for adding a Frame or Canvas to the window before adding any widgets, and then adding widgets to that Frame or Canvas.  This was particularly advised when using widgets from the ttk set.  So, perhaps there is a reason for that in that it fixes some issues.  Glad you got it working.
