### ISSUE TITLE
API_server

### ISSUE THREAD

**Issue by JellyEvan** [JellyEvan/547final_jks#22]
@wesleyk-duke 

so the app will POST a string in the following form
```     
app_to_server = { "RAW_image": RAW, "BG_image": BG, "disp_b": b, "disp_c": c} 
```
where `RAW` and  `BG` are b64encoded strings
and `b` and `c` are user entered dispersion coefficients

then I'll need a GET location to pickup the processed image

**Comment by wesleyk-duke** [comment]
So should this instead be 

```app_to_server = { "RAW_image": RAW, "disp_b": b, "disp_c": c} ```

**Comment by wesleyk-duke** [comment]
Also I think this would be better for identifying the files:

```app_to_server = { "Filename": filename, "RAW_image": RAW, "disp_b": b, "disp_c": c}```

**Comment by JellyEvan** [comment]
ok will update

**Comment by JellyEvan** [comment]
@wesleyk-duke, what filename do you want? the RAW image file?

**Comment by wesleyk-duke** [comment]
yeah, we might want the filename to be customizable

**Comment by wesleyk-duke** [comment]
and even if not the RAW variable is always going to be called RAW so we should be able to identify unique filenames

**Comment by JellyEvan** [comment]
![Alt Text](https://i.giphy.com/media/GCvktC0KFy9l6/giphy.webp)

**Comment by wesleyk-duke** [comment]
@JellyEvan @gs172 uploaded a file ```test_file_API.py``` you can use to see how to interact with the server. I can't get the code at the bottom to work in a function if the code is in a different file so I'm still working on that but this should be enough to start integrating the GUI/other stuff with the server
