### ISSUE TITLE
adapt processing functions to accept all spectrum sizes

### ISSUE THREAD

**Issue by gs172** [JellyEvan/547final_jks#28]
I changed all processing functions to be flexible to any sized client-input raw spectrum, instead of the standard 1024x512

**Comment by gs172** [comment]
@wesleyk-duke @JellyEvan 
The processing functions now accept client input raw spectrum of any size(not necessarily 1024x512).

**Comment by wesleyk-duke** [comment]
this should be something the GUI or otherwise automatically takes the dimensions of so that the processed image can be resized from a string to the right dimension

**Comment by JellyEvan** [comment]
the size of the file is encoded in the string, so if you need the file dimensions when you decode to an image file, you should be able to find or write a small module that returns the file size

the less information we send from client to server and vice versa the better i think

**Comment by wesleyk-duke** [comment]
the total pixel size is but not the individual row/column size.

**Comment by JellyEvan** [comment]
@wesleyk-duke i added the dimension before bed, looked at your file added it the way you called it
```python
    output = {
              "Filename": filename,
              "RAW_image": RAW,
              "disp_b": b,
              "disp_c": c,
              "xdim": x,
              "ydim": y
              }
```
