### ISSUE TITLE
Code stops working when moved to another file

### ISSUE THREAD

**Issue by wesleyk-duke** [JellyEvan/547final_jks#39]
[547final_jks.zip](https://github.com/JellyEvan/547final_jks/files/3104852/547final_jks.zip)

To reproduce:

1. Download contents of zip file
2. Execute file ```API_OCT_processing.py``` as flask server
3. Execute file ```test_file_API.py``` to see code not working
4. Uncomment out code underneath "# UNCOMMENT 2" and then comment out the code underneath "# UNCOMMENT 1" to see code working as intended

For some reason, the same code does not work in a different file. Do you have any suggestions?

**Comment by dward2** [comment]
I don't want to have to download your zip file.  I want to clone your repository and run files from there.  Why?  Because I need to set up a virtual environment just like yours, and I need your requirements.txt file to do it.  So, in general, you should put a link in your issue to the code you want me to run, so I know exactly what file and branch to use.  For example, I believe you want me to run this file:

https://github.com/JellyEvan/547final_jks/blob/111d68afab8e0dcb8c316877a63da9b4a177571b/API_OCT_processing.py#L106

Then, this file:
https://github.com/JellyEvan/547final_jks/blob/111d68afab8e0dcb8c316877a63da9b4a177571b/test_file_API.py#L1

But, I don't see your UNCOMMENT 2 and UNCOMMENT 1 in any of your online files.  Please push that to GitHub and then include links to the appropriate lines.

If you are not sure how to link code, please see <https://help.github.com/en/articles/creating-a-permanent-link-to-a-code-snippet>.

**Comment by dward2** [comment]
FYI, when I run `test_file_API.py` after having started the server, I get the following error:
```
Traceback (most recent call last):
  File "D:/ClassRepos/FinalProject/jelly_kendall_song/test_file_API.py", line 27, in <module>
    raw, w, h = oct.read_in_raw(filename)
TypeError: read_in_raw() takes 0 positional arguments but 1 was given
```

**Comment by wesleyk-duke** [comment]
Dr. Ward,

I've updated the code in the github branch "API_functions_WK":

https://github.com/JellyEvan/547final_jks/blob/API_functions_WK/API_OCT_processing.py
https://github.com/JellyEvan/547final_jks/blob/API_functions_WK/OCT_processing.py
https://github.com/JellyEvan/547final_jks/blob/API_functions_WK/test_file_API.py

The UNCOMMENT 1/2 code is in line 51 and 55-62 on test_file_API.py. 

Let me know if you have any other issues replicating this problem

**Comment by dward2** [comment]
Okay, I duplicated your issue.  Let me take a look at it.  Are you also getting the error:

```
Traceback (most recent call last):
  File "D:/ClassRepos/FinalProject/jelly_kendall_song/test_file_API.py", line 51, in <module>
    a, b, c, d, e = apioct.get_file(filename)
  File "D:\ClassRepos\FinalProject\jelly_kendall_song\API_OCT_processing.py", line 57, in get_file
    return a, b, c, d, e
UnboundLocalError: local variable 'a' referenced before assignment
```

**Comment by wesleyk-duke** [comment]
Yes, this is exactly the issue I am having problems with. 

The for loop in "apioct.get_file" does not run at all because the QuerySet variable ```titles``` in that function seems to be empty, but I am not sure why it is empty.

**Comment by dward2** [comment]
This is probably the issue I brought up in class.  You cannot define the MongoDB class twice.  What is happening is that your `test_file_API.py` is using the `RawFile` class defined in itself.  So, when it is put into the MongoDB, it is stored as a type `test_file_API.RawFile`.  Then, in your `API_OCT_processing.py` file, you are trying to access files using the `RawFile` class defined in that file, and MongoDB views that as `API_OCT_processing.RawFile`.  So, you are saving the files in one place in your MongoDB, and then trying to access them in another place.

This is why I said in class that you need to do the following.  You should only define the MongoModel class once, and you should do it in a separate file.  Then, every other file that needs access to this class should import it from that file.  So, copy your `RawFile` class definition and put it in a file with a name like `class_defintion.py` or whatever you want.  Then, in any file that needs access to this class, include `from class_definition import RawFile`.

Try that and it should fix your problem.  If not, let me know.

**Comment by wesleyk-duke** [comment]
I have implemented your solution in the code that was uploaded to GitHub, but unfortunately it does not seem to work. 

In fact, I can't get the code in UNCOMMENT 2 to work while referencing the ```RawFile``` class in the other folder; it only works when it is in the same file ```test_file_API.py```. 

The function I have to upload files to MongoDB (```api_read_in_raw()``` in ```API_OCT_processing.py```) works just fine whether or not the ```RawFile``` class is in the file itself or referenced in ```class_definition.py```.

**Comment by wesleyk-duke** [comment]
I resolved the issue by switching to ```pymongo``` instead of ```pymodm```.

**Comment by dward2** [comment]
Great.
